language: node_js
node_js: node

env:
  - DB=postgres
  - JWT_SECRET="munchstats-jwt-secret"

services:
  - postgresql

before_script:
  - psql -U postgres -c 'create database "munchstats-test";'
  - npm run migrate