language: node_js
node_js: node

env:
  - DB=postgres
  - FOOD_API_URI_START=https://api.edamam.com/api/food-database/parser?ingr=
  - FOOD_API_URI_END=&app_id=94987ad8&app_key=f087d3111d3d6454e43e303f35150db5
  - NUTRITION_API_URI=https://api.edamam.com/api/food-database/nutrients?app_id=94987ad8&
  - JWT_SECRET=munchstats-jwt-secret

services:
  - postgresql

before_script:
  - psql -U postgres -c 'create database "munchstats-test";'
  - npm run migrate