language: node_js
node_js: node

services:
  - postgresql

postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres

before_script:
  - psql -U postgres -c 'create database "munchstats-test";'
  - "rake db:migrate"