language: node_js
node_js: node

services:
  - postgresql

before_script:
  - psql -U postgres -c 'create database "munchstats-test";'
  - npm run build
  - npm install -g sequelize-cli
  - sequelize db:migrate